version: '3.8'
services:
  stats-service:
    build: stats-service
    image: stats-service
    container_name: stats-service
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats-service
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=iamroot

  stats-db:
    image: postgres:13.7-alpine
    container_name: stats-db
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stats-service
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=iamroot

  main-service:
    build: main-service
    image: main-service
    container_name: main-service
    ports:
      - "8080:8080"
    depends_on:
      - main-db
    environment:
      - STATS_SERVER_URL=http://stats-server:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://main-db:5432/main-service
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=iamroot

  main-db:
    image: postgres:13.7-alpine
    container_name: main-db
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=main-service
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=iamroot